# Generated by Django 4.2.7 on 2026-03-04 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_comment_is_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA Habilitado'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(choices=[('TOTP', 'TOTP'), ('SMS', 'SMS')], default='TOTP', max_length=20, verbose_name='Método 2FA'),
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_key', models.CharField(max_length=32, verbose_name='Clave Secreta')),
                ('backup_codes', models.JSONField(default=list, verbose_name='Códigos de Recuperación')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Uso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '2FA',
                'verbose_name_plural': '2FAs',
                'db_table': 'two_factor_auth',
            },
        ),
    ]
