# Generated by Django 4.2.7 on 2026-03-04 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0005_user_two_factor_enabled_user_two_factor_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_tickets', models.BooleanField(default=True, verbose_name='Notificaciones de tickets por email')),
                ('email_documents', models.BooleanField(default=True, verbose_name='Notificaciones de documentos por email')),
                ('email_projects', models.BooleanField(default=True, verbose_name='Notificaciones de proyectos por email')),
                ('email_comments', models.BooleanField(default=True, verbose_name='Notificaciones de comentarios por email')),
                ('email_security', models.BooleanField(default=True, verbose_name='Alertas de seguridad por email')),
                ('email_system', models.BooleanField(default=True, verbose_name='Anuncios del sistema por email')),
                ('digest_frequency', models.CharField(choices=[('IMMEDIATE', 'Inmediato'), ('HOURLY', 'Cada hora'), ('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('NEVER', 'Nunca')], default='IMMEDIATE', max_length=20, verbose_name='Frecuencia de resumen')),
                ('show_in_dashboard', models.BooleanField(default=True, verbose_name='Mostrar en dashboard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de notificación',
                'verbose_name_plural': 'Preferencias de notificacion',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('TICKET_CREATED', 'Ticket creado'), ('TICKET_UPDATED', 'Ticket actualizado'), ('TICKET_RESOLVED', 'Ticket resuelto'), ('DOCUMENT_SHARED', 'Documento compartido'), ('DOCUMENT_UPDATED', 'Documento actualizado'), ('PROJECT_CREATED', 'Proyecto creado'), ('PROJECT_UPDATED', 'Proyecto actualizado'), ('USER_ASSIGNED', 'Usuario asignado'), ('COMMENT_POSTED', 'Comentario publicado'), ('2FA_ENABLED', '2FA habilitado'), ('2FA_DISABLED', '2FA deshabilitado'), ('LOGIN_ALERT', 'Alerta de login'), ('SECURITY_ALERT', 'Alerta de seguridad'), ('SYSTEM_ANNOUNCEMENT', 'Anuncio del sistema')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('email_sent', models.BooleanField(default=False)),
                ('email_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('FAILED', 'Fallido'), ('READ', 'Leído')], default='PENDING', max_length=20)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['email_status', 'email_sent'], name='notificatio_email_s_8f1006_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx')],
            },
        ),
    ]
