# Generated by Django 4.2.7 on 2026-05-21 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_user_two_factor_enabled_user_two_factor_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIGRAEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('LOGIN', 'Login'), ('DOWNLOAD_DOC', 'Document Download'), ('UPLOAD_DOC', 'Document Upload'), ('EDIT_DOC', 'Document Edit'), ('DELETE_DOC', 'Document Delete'), ('CHANGE_PERMISSION', 'Permission Change'), ('FAILED_LOGIN', 'Failed Login'), ('DENIED_ACCESS', 'Denied Access')], max_length=100)),
                ('event_data', models.JSONField(default=dict)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('scoring_breakdown', models.JSONField(default=dict, help_text='Desglose de cómo se calculó el score')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('audit_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit.auditlog')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sigra_events', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sigra_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SIGRA Event',
                'verbose_name_plural': 'SIGRA Events',
                'db_table': 'sigra_events',
            },
        ),
        migrations.CreateModel(
            name='SIGRAAlert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('ANOMALOUS_TIME', 'Access Outside Business Hours'), ('UNKNOWN_IP', 'Access From Unknown IP'), ('UNKNOWN_DEVICE', 'Access From Unknown Device'), ('FAILED_LOGINS', 'Multiple Failed Logins'), ('MASS_DOWNLOAD', 'Mass Document Download'), ('CRITICAL_DOC_ACCESS', 'Critical Document Access'), ('PERMISSION_CHANGE', 'Suspicious Permission Change'), ('ROLE_ANOMALY', 'Action Incompatible With Role'), ('EXPORT_ATTEMPT', 'Data Export Attempt')], max_length=100)),
                ('severity', models.CharField(choices=[('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(default=dict, help_text='Contexto completo del evento que disparó la alerta')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=50)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_escalated', models.BooleanField(default=False)),
                ('incident_ticket_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sigra_alerts', to='companies.company')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('sigra_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='sigra.sigraevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sigra_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SIGRA Alert',
                'verbose_name_plural': 'SIGRA Alerts',
                'db_table': 'sigra_alerts',
            },
        ),
        migrations.AddIndex(
            model_name='sigraevent',
            index=models.Index(fields=['company', 'created_at'], name='sigra_event_company_1f3147_idx'),
        ),
        migrations.AddIndex(
            model_name='sigraevent',
            index=models.Index(fields=['user', 'created_at'], name='sigra_event_user_id_2afc5c_idx'),
        ),
        migrations.AddIndex(
            model_name='sigraevent',
            index=models.Index(fields=['risk_level', 'created_at'], name='sigra_event_risk_le_fa18b8_idx'),
        ),
        migrations.AddIndex(
            model_name='sigraalert',
            index=models.Index(fields=['status', 'severity', 'created_at'], name='sigra_alert_status_caca3e_idx'),
        ),
        migrations.AddIndex(
            model_name='sigraalert',
            index=models.Index(fields=['user', 'status'], name='sigra_alert_user_id_54e28a_idx'),
        ),
        migrations.AddIndex(
            model_name='sigraalert',
            index=models.Index(fields=['company', 'created_at'], name='sigra_alert_company_0ffa12_idx'),
        ),
    ]
